# Generated by Django 5.2.13 on 2026-05-05 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('nivel_acesso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('companhia_aerea', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('piloto', 'Piloto'), ('atendente', 'Atendente'), ('seguranca', 'Segurança')], max_length=20)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_passaporte', models.CharField(max_length=20, unique=True)),
                ('data_nascimento', models.DateField()),
                ('contato', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortaoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_portao', models.CharField(max_length=10, unique=True)),
                ('localizacao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupado', 'Ocupado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('atraso', 'Alerta de atraso'), ('mudanca_portao', 'Mudança de portão')], max_length=20)),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.passageiro')),
            ],
        ),
        migrations.CreateModel(
            name='Bagagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('despachada', 'Despachada'), ('em_transito', 'Em trânsito'), ('entregue', 'Entregue')], max_length=20)),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.passageiro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assento', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.passageiro')),
            ],
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_voo', models.CharField(max_length=20, unique=True)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('partida', models.DateTimeField()),
                ('chegada', models.DateTimeField()),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.aeronave')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='voo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.voo'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('realizado', 'Realizado'), ('pendente', 'Pendente')], max_length=20)),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.passageiro')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.voo')),
            ],
        ),
    ]
