# Generated by Django 5.2.13 on 2026-05-26 02:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('nivel_acesso', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Administrador (legado)',
                'verbose_name_plural': 'Administradores (legado)',
            },
        ),
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade (passageiros)')),
                ('companhia_aerea', models.CharField(max_length=100, verbose_name='Companhia aérea')),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
            },
        ),
        migrations.CreateModel(
            name='PortaoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_portao', models.CharField(max_length=10, unique=True, verbose_name='Número do portão')),
                ('localizacao', models.CharField(max_length=100, verbose_name='Localização')),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupado', 'Ocupado')], max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Portão de Embarque',
                'verbose_name_plural': 'Portões de Embarque',
            },
        ),
        migrations.CreateModel(
            name='UsuarioCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('passageiro', 'Passageiro'), ('funcionario', 'Funcionário'), ('administrador', 'Administrador')], default='passageiro', max_length=20, verbose_name='Tipo de usuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cargo', models.CharField(choices=[('piloto', 'Piloto'), ('atendente', 'Atendente'), ('seguranca', 'Segurança')], max_length=20, verbose_name='Cargo')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('contato', models.CharField(max_length=100, verbose_name='Telefone / Contato')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf_passaporte', models.CharField(max_length=20, unique=True, verbose_name='CPF / Passaporte')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('contato', models.CharField(max_length=100, verbose_name='Telefone / Contato')),
                ('nacionalidade', models.CharField(max_length=50, verbose_name='Nacionalidade')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passageiro', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('tipo', models.CharField(choices=[('atraso', 'Alerta de atraso'), ('mudanca_portao', 'Mudança de portão'), ('cancelamento', 'Cancelamento de voo'), ('geral', 'Informação geral')], max_length=20, verbose_name='Tipo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.passageiro', verbose_name='Passageiro')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assento', models.CharField(max_length=10, verbose_name='Assento')),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Status')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.passageiro', verbose_name='Passageiro')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código do bilhete')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de emissão')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Bilhete',
                'verbose_name_plural': 'Bilhetes',
            },
        ),
        migrations.CreateModel(
            name='Bagagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('status', models.CharField(choices=[('despachada', 'Despachada'), ('em_transito', 'Em trânsito'), ('entregue', 'Entregue')], max_length=20, verbose_name='Status')),
                ('numero_rastreio', models.CharField(max_length=20, unique=True, verbose_name='Número de rastreio')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagagens', to='skybridgeapp.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Bagagem',
                'verbose_name_plural': 'Bagagens',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_voo', models.CharField(max_length=20, unique=True, verbose_name='Número do voo')),
                ('origem', models.CharField(max_length=100, verbose_name='Origem')),
                ('destino', models.CharField(max_length=100, verbose_name='Destino')),
                ('partida', models.DateTimeField(verbose_name='Partida')),
                ('chegada', models.DateTimeField(verbose_name='Chegada')),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('atrasado', 'Atrasado'), ('em_andamento', 'Em andamento'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Status')),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.aeronave', verbose_name='Aeronave')),
                ('portao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voos', to='skybridgeapp.portaoembarque', verbose_name='Portão de embarque')),
            ],
            options={
                'verbose_name': 'Voo',
                'verbose_name_plural': 'Voos',
                'ordering': ['partida'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='voo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.voo', verbose_name='Voo'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('status', models.CharField(choices=[('realizado', 'Realizado'), ('pendente', 'Pendente')], max_length=20, verbose_name='Status')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.passageiro', verbose_name='Passageiro')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skybridgeapp.voo', verbose_name='Voo')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
            },
        ),
    ]
