# Generated by Django 5.2.13 on 2026-05-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skybridgeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iata', models.CharField(max_length=3, unique=True, verbose_name='Codigo IATA')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Aeroporto',
                'verbose_name_plural': 'Aeroportos',
                'ordering': ['codigo_iata'],
            },
        ),
        migrations.CreateModel(
            name='CompanhiaAerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo_iata', models.CharField(max_length=3, unique=True, verbose_name='Codigo IATA')),
                ('pais', models.CharField(max_length=50, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Companhia aerea',
                'verbose_name_plural': 'Companhias aereas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaMilhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(default=0, verbose_name='Saldo')),
                ('numero_programa', models.CharField(max_length=30, unique=True, verbose_name='Numero do programa')),
                ('passageiro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_milhas', to='skybridgeapp.passageiro', verbose_name='Passageiro')),
            ],
            options={
                'verbose_name': 'Conta de milhas',
                'verbose_name_plural': 'Contas de milhas',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('metodo', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartao'), ('boleto', 'Boleto'), ('milhas', 'Milhas')], max_length=20, verbose_name='Metodo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='skybridgeapp.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('preco_a_partir_de', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco a partir de')),
                ('data_inicio', models.DateField(verbose_name='Data de inicio')),
                ('data_fim', models.DateField(verbose_name='Data de fim')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_destino', to='skybridgeapp.aeroporto', verbose_name='Destino')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_origem', to='skybridgeapp.aeroporto', verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Promocao',
                'verbose_name_plural': 'Promocoes',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium economy'), ('executiva', 'Executiva')], max_length=20, verbose_name='Classe')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco base')),
                ('taxas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxas')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='skybridgeapp.voo', verbose_name='Voo')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
        migrations.CreateModel(
            name='TransacaoMilhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acumulo', 'Acumulo'), ('resgate', 'Resgate'), ('expiracao', 'Expiracao')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='skybridgeapp.contamilhas', verbose_name='Conta de milhas')),
            ],
            options={
                'verbose_name': 'Transacao de milhas',
                'verbose_name_plural': 'Transacoes de milhas',
                'ordering': ['-data'],
            },
        ),
    ]
