# Generated by Django 5.2.13 on 2026-06-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skybridgeapp', '0002_aeroporto_companhiaaerea_contamilhas_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='classe_tarifa',
            field=models.CharField(blank=True, choices=[('economy', 'Economy'), ('premium_economy', 'Premium economy'), ('executiva', 'Executiva')], default='', max_length=20, verbose_name='Classe da tarifa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quantidade_passageiros',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de passageiros'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Status'),
        ),
    ]
