# Generated by Django 5.2.13 on 2026-06-08 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skybridgeapp', '0004_promove_administradores_para_superusuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('somente_ida', 'Somente ida'), ('ida_volta', 'Ida e volta')], default='somente_ida', max_length=20, verbose_name='Tipo de viagem')),
                ('classe_tarifa', models.CharField(blank=True, choices=[('economy', 'Economy'), ('premium_economy', 'Premium economy'), ('executiva', 'Executiva')], default='', max_length=20, verbose_name='Classe da tarifa')),
                ('quantidade_passageiros', models.PositiveIntegerField(default=1, verbose_name='Quantidade de passageiros')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='skybridgeapp.passageiro', verbose_name='Passageiro')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='viagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='skybridgeapp.viagem', verbose_name='Viagem'),
        ),
    ]
