# Generated by Django 5.2.13 on 2026-06-10 01:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skybridgeapp', '0005_viagem_reserva_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagagem',
            name='tipo',
            field=models.CharField(choices=[('mao', 'Bagagem de mão (10kg)'), ('despachada', 'Bagagem despachada (23kg)')], default='despachada', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quantidade_bagagem_despachada',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de bagagem despachada'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quantidade_bagagem_mao',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de bagagem de mão'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='taxa_bagagem',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Taxa de bagagem'),
        ),
        migrations.AlterField(
            model_name='bagagem',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='bagagem',
            name='status',
            field=models.CharField(choices=[('declarada', 'Declarada'), ('recebida', 'Recebida no balcão'), ('em_transito', 'Em trânsito'), ('entregue', 'Entregue')], default='declarada', max_length=20, verbose_name='Status'),
        ),
    ]
