from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('acesso/', views.auth_home, name='auth_home'),
    path('status-voo/', views.status_voo, name='status_voo'),
    path('voos/buscar/', views.buscar_voos, name='buscar_voos'),
    path('voos/datas/', views.buscar_voos_datas, name='buscar_voos_datas'),
    path('voos/<int:voo_id>/', views.detalhe_voo, name='detalhe_voo'),
    path('voos/<int:voo_id>/selecionar/', views.selecionar_voo, name='selecionar_voo'),
    path('voos/<int:voo_id>/reservar/', views.criar_reserva, name='criar_reserva'),
    path('reservas/<int:reserva_id>/pagamento/', views.pagamento_reserva, name='pagamento_reserva'),
    path('reservas/<int:reserva_id>/sucesso/', views.reserva_sucesso, name='reserva_sucesso'),
    path('reservas/<int:reserva_id>/bilhete/', views.bilhete_reserva, name='bilhete_reserva'),
    path('reservas/<int:reserva_id>/check-in/', views.realizar_checkin, name='realizar_checkin'),
    path('reservas/<int:reserva_id>/cartao-embarque/', views.cartao_embarque, name='cartao_embarque'),
    path('minhas-viagens/', views.minhas_viagens, name='minhas_viagens'),
    path('reservas/<int:reserva_id>/', views.detalhe_reserva, name='detalhe_reserva'),
    path('reservas/<int:reserva_id>/cancelar/', views.cancelar_reserva, name='cancelar_reserva'),
    path('notificacoes/', views.notificacoes_passageiro, name='notificacoes_passageiro'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.SkyBridgeLoginView.as_view(), name='login'),
    path('logout/', views.SkyBridgeLogoutView.as_view(), name='logout'),
    path('senha/redefinir/', views.SkyBridgePasswordResetView.as_view(), name='password_reset'),
    path('senha/redefinir/enviado/', views.SkyBridgePasswordResetDoneView.as_view(), name='password_reset_done'),
    path('senha/redefinir/<uidb64>/<token>/', views.SkyBridgePasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('senha/redefinir/concluido/', views.SkyBridgePasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('senha/alterar/', views.SkyBridgePasswordChangeView.as_view(), name='password_change'),
    path('senha/alterar/concluido/', views.SkyBridgePasswordChangeDoneView.as_view(), name='password_change_done'),
    path('dashboard/', views.dashboard_router, name='dashboard'),
    path('dashboard/passageiro/', views.dashboard_passageiro, name='dashboard_passageiro'),
    path('dashboard/funcionario/', views.dashboard_funcionario, name='dashboard_funcionario'),
    path('dashboard/funcionario/voos/<int:voo_id>/atualizar/', views.atualizar_voo_operacional, name='atualizar_voo_operacional'),
    path('dashboard/administrador/', views.dashboard_administrador, name='dashboard_administrador'),
]
